### ISSUE TITLE
wrong compile command in Bageritz_2019/README.md

### ISSUE THREAD

**Issue by ghuls** [boutroslab/Supplemental-Material#2]
In `Bageritz_2019/README.md`:

`gcc 4_calculate_expression_maps.c -o 4_calculate_expression_maps.c -lm`

Should be:
`gcc 4_calculate_expression_maps.c -o 4_calculate_expression_maps -lm`

**Comment by eturkes** [comment]
`gcc 3_cross_correlation_to_mapping_genes.c -o 3_cross_correlation_to_mapping_genes`

should also be:

`gcc 3_cross_correlation_to_mapping_genes.c -o 3_cross_correlation_to_mapping_genes -lm`

**Comment by ericavalentini** [comment]
Thanks a lot for spotting the errors! We modified the README accordingly.
